# Example api requests

## Media resource

### Get all media
GET http://localhost:3000/api/media

### Get a media item based on id
GET http://localhost:3000/api/media/9632?format=plain

### 2nd version
GET http://localhost:3000/api/media/9632
### test not found
GET http://localhost:3000/api/media/963

### Create an item
POST http://localhost:3000/api/media
Content-Type: application/json

### Fetch all likes for a specific media item.
GET http://localhost:3000/api/likes/media/:id
### Fetch all likes for a specific user.
GET http://localhost:3000/api/likes/user/:id
### Add a like
POST http://localhost:3000/api/likes/
Content-Type: application/json
{
    "username": "JohnDoe",
    "password": "to-be-hashed-pw1"
}
### Remove likes by id

## User authentication

### Register
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "username": "Aldi",
  "password": "AiMagic",
  "email": "Vultures3245@ye.com"
}

### Login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "JohnDo",
  "password": "password123",
}

### Get my user info
GET http://localhost:3000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJpYXQiOjE3MzE5MjA1MDYsImV4cCI6MTczMjAwNjkwNn0.lsH2IFBtX7K83PGTaUfor3LWOgaGPPRflTA5kbCvVeA

## Media resource

### Get all media
GET http://localhost:3000/api/media

### Get a media item based on id
GET http://localhost:3000/api/media/4
### Get media item FAIL (id not found)
GET http://localhost:3000/api/media/96399

### Create an item
POST http://localhost:3000/api/media
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo5LCJpYXQiOjE3MzI1MjQ4ODksImV4cCI6MTczMjYxMTI4OX0.AxOzq2Jrjn-pgnYtECZ0TNjHxG57k8QSvyrtcADtu4Q
Content-Type: multipart/form-data; boundary=----Boundary

------Boundary
Content-Disposition: form-data; name="title"

New Dexter image
------Boundary
Content-Disposition: form-data; name="description"

Kiva kuva ystävällisestä rikospaikka tutkijasta.
------Boundary
Content-Disposition: form-data; name="file"; filename="image.png"
Content-Type: image/png

< ./dexter.webp
------Boundary--

### Create an item FAIL (title missing)
POST http://localhost:3000/api/media
Content-Type: multipart/form-data; boundary=----Boundary

------Boundary
Content-Disposition: form-data; name="description"

Kiva kuva kissasta.
------Boundary
Content-Disposition: form-data; name="file"; filename="image.png"
Content-Type: image/png

< ./dexter.webp
------Boundary--

### Update an item
PUT http://localhost:3000/api/media/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJpYXQiOjE3MzE5MjA1MDYsImV4cCI6MTczMjAwNjkwNn0.lsH2IFBtX7K83PGTaUfor3LWOgaGPPRflTA5kbCvVeA

{
  "title": "Muokattu kuva",
  "description": "Tosi kiva."
}

### Get user info to test authentication
GET http://localhost:3000/api/auth/me
Authorization: Bearer <your_jwt_token>

### Fixed registration of new user
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "username": "DoeJoe",
  "password": "Monkey123",
  "email": "doejoe@example.com",
  "user_level_id": 2
}